language: node_js
node_js:
- '8'
before_install:
- npm install jsdoc npm@latest -g
install:
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/doc.js"
- "./ci/test.js"
before_deploy:
  - NODE_ENV=development npm i
  - git clean -f
deploy:
  provider: npm
  email: oss@realglobe.jp
  api_key:
    secure: e5c9Brq/aWrvLjw5h9oqg1vm/dPYHPopDimq8pIvbE3scLXrGjllhXnt+rM6yeW6d4uQJ0gs5k71Z/nw/ZPqSyheVCGIfj3mesC2b+We34UAZ2SKlCGy854Bo9c0v4hVmg/wREJl3/zWbCkFFF1XxcRf44baDH9evLEi7LKikzmxz9CO62xSem35qRf2DAiyY0HesRjsjnNbAYEsE3Gv503PB4nRN7DDhj/eacNi4QKxjrQpFXyhaImKgaRU2aIXO9SvVUX49tETTUogKRV4VdeqJz+8KWFHLdhHytECkHPwbR2MctazjQRtwxw/NM37KaX6IIFtkqtZir0uvvO1SOFh2LYwGJKVYpOmpijj1Kgwt0vyqbpTsqxc1RPdL7x+kXwukBv+AvsnxF23r7u74fiqdM3mVfldwds4xHbXuMb4U2WRGt+lqv8+XZTZhBjpNp99HIDXNvK52zMV7BVG3qX2qO7aVYthBxYj76q4HO08cCzBM+Y9DBAs4uD8HTqUojfGH1cthc7bqMcPuI2MeUXPHGCgw7b4iGnaW1J8dC9cIgHTPnqY4ZBxJoSdkAONuikZT0QkYo1eFKIzB5GHnsNTt4VtJxK3J9baDTab+yuyb8B3D/qO0MNFBlfL/ToIZBOcL0RrZWIilH0mE/HxzXOHVz0T3hn+SpjHOr7ZsA8=
